name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: ramsey/composer-install@v3
      - run: composer test
      - run: composer test:integration
      - run: composer test:acceptance-coverage
